Update reset.css
yanaskey/test3 pull request #4
Opened 2023-02-18 21:14 UTC by yanaskey

2023-02-18 22:17 UTC, OlenaOP commented on src/css/reset.css
>    margin-left: auto;
на мобільній версії padding-right: 20px;
  padding-left: 20px;

2023-02-18 22:35 UTC, OlenaOP requested changes

2023-02-18 22:35 UTC, OlenaOP commented on src/css/reset.css
> +  }
мабуть потрібно додати  в 
@media screen and (min-width: 768px) {
  .container {
    width: 768px;
  }
падінги:
padding-right: 32px;
  padding-left: 32px;

2023-02-18 22:35 UTC, OlenaOP commented on src/css/reset.css
> +
додати медіазапит
@media screen and (min-width: 768px) {
 .section-title {
  font-size: 68px;
  }   }

2023-02-18 22:35 UTC, OlenaOP commented on src/css/reset.css
не можу прокоментувати нижче, але мені здається колір фону в :root не такий --background-color: #d8d8d8;
, а такий 
--background-color: #f6f6f6;

2023-02-18 22:35 UTC, OlenaOP commented on src/css/reset.css
> +}
мало інформації, я б додала ще як мінімум таке:
font-family: inherit;
font-weight: 500;
і колір:
color: var(--black-text-color);

2023-02-18 22:54 UTC, yanaskey commented on src/css/reset.css
> +}
я хотіла додати font-weight, але він змінюється з 400 до 500, тому щоб не було помилок, то не вказувала; на рахунок кольору, то на макеті є три варіанти кольору, чи є прописувати основний? білий чорний плюс-мінус з однаковою частотою використовуються. font-family хіба не наслідується за замовчуванням? він прописаний вище

2023-02-18 23:06 UTC, yanaskey commented on src/css/reset.css
background-color для всього проекту: #d8d8d8; він відрізняється тільки для секції хіро, і там він дійсно #f6f6f6;

2023-02-18 23:12 UTC, OlenaOP commented on src/css/reset.css
> +}
з приводу кольору. білий колір я бачу лише в одному місці на сторінці home у секції hotel і наче все.
з приводу font-weight дивлячись на що ми будемо навішувати цей стиль. 
я його бачу лише для 3х секцій на сторінці home 
якщо ти планувала його використовувати у hero на трьох інших сторінках, та так, там дійсно font-weight 400, але й розмір шрифту інший, тож навіть не знаю.
font-family дійсно начеб-то наслідується, можемо не писати.

2023-02-18 23:13 UTC, yanaskey commented on src/css/reset.css
>    margin-left: auto;
в усіх версіях падінги 32

2023-02-18 23:19 UTC, yanaskey commented on src/css/reset.css
> +  }
Виправлено

2023-02-18 23:19 UTC, yanaskey commented on src/css/reset.css
> +
Виправлено

2023-02-19 00:53 UTC, yanaskey commented on src/css/reset.css
> +}
в нас ще є секції з білим текстом на сторінці Ресторан та Рум - але так само як чорний текст іноді #121212, а іноді #000000; білий текст іноді #f7f7f7, а іноді #f6f6f6
вони усі внесені краще вже хай кожен обирає колір по макету під кожну секцію

2023-02-19 09:08 UTC, shinitern commented on src/css/reset.css
> +    width: 1140px;
ширина 1440*

2023-02-19 14:04 UTC, merged